build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  TooManyFunctions:
    active: false
  LargeClass:
    active: false
  LongMethod:
    threshold: 80

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
  UnusedImports:
    active: true
  WildcardImport:
    active: true

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
