complexity:
  TooManyFunctions:
    active: false
  LargeClass:
    active: false
  LongMethod:
    allowedLines: 80

style:
  MagicNumber:
    active: false
  UnusedImport:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateFunction:
    active: true
  UnusedPrivateProperty:
    active: true
  WildcardImport:
    active: true

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
